name:                wordbrain
version:             0.1.0.0
#synopsis:
#description:
homepage:            https://github.com/githubuser/wordbrain#readme
license:             BSD3
author:              Author name here
maintainer:          example@example.com
copyright:           2019 Author name here
category:            Web
extra-source-files:
- README.md

dependencies:
  - base >= 4.7 && < 5

dependencies:
  - containers
  - bytestring-trie
  - bytestring
  - base
  - file-embed

library:
  source-dirs:      src

tests:
  wordbrain-tests:
    main: main.hs
    source-dirs: [test]
    dependencies:
      - wordbrain
      - hspec
      - QuickCheck
      - raw-strings-qq


benchmarks:
  wordbrain-bench:
    main: main.hs
    source-dirs: [bench]
    dependencies:
      - wordbrain
      - criterion
      - raw-strings-qq
